# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.09672023 0.77219947 0.28861618]
  [0.22636374 0.9868405  0.22290374]
  [0.70622746 0.44102135 0.37561902]]

 [[0.70268863 0.93651259 0.21222766]
  [0.92324932 0.21508547 0.44321486]
  [0.16107874 0.39441476 0.06030408]]

 [[0.00249237 0.6056077  0.80271206]
  [0.68230816 0.35456929 0.43807109]
  [0.02578234 0.39443334 0.12310745]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)



Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.62952784 0.71430081 0.24664133 0.51436668 0.26516832]
 [0.76177096 0.44935733 0.05150334 0.99704309 0.34654376]
 [0.86941619 0.83255535 0.00377125 0.36788788 0.27766419]
 [0.48373859 0.52783103 0.53931038 0.19959056 0.38543932]
 [0.01121905 0.43100273 0.90119708 0.7628692  0.39606109]]
After normalization:
[[0.6299953  0.7153425  0.24451522 0.51405406 0.2631677 ]
 [0.7631342  0.44860436 0.04805541 1.         0.34509436]
 [0.87150859 0.83439806 0.         0.36658306 0.27574822]
 [0.48321852 0.52760962 0.53916673 0.19714574 0.38425338]
 [0.00749825 0.43012543 0.90350476 0.76423988 0.3949471 ]]


# 5.  How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [8]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 0 0 0 1]
Second array:
[0 1 1 0 0 1]
Test above two arrays are equal
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [15]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.32901253 0.38467817 0.96719439 0.09881841 0.65371433 0.23293341
 0.41154759 0.72295964 0.88097422 0.09134594]
Maximum value replaced by 0:
[0.32901253 0.38467817 0.         0.09881841 0.65371433 0.23293341
 0.41154759 0.72295964 0.88097422 0.09134594]


# 9. How to print all the values of an array?

In [13]:
my_array = np. arange(10)
print(my_array)
np. set_printoptions(threshold=np. inf)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [19]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(2, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.51431488 0.28055943 0.60464981]
 [0.144396   0.41606559 0.38258458]]

Subtract the mean of each row of the said matrix:

[[ 0.04780684 -0.18594861  0.13814178]
 [-0.16995272  0.10171687  0.06823585]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [28]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 5. 4. 3. 3. 3. 3. 2. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [34]:
import numpy as np  
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
print("this will give dot product")
res = np.dot(mat1,mat2)
print(res)
print("this will give the diagonal of the dot product")
np.diag(res)

this will give dot product
[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
this will give the diagonal of the dot product


array([ 63, 484, 117])

# 13.How to find the most frequent value in an array?

In [27]:
import numpy as np
x = np.random.randint(0, 10, 10)
print("Original array:")
print(x)
print("Most frequent value")
print(np.bincount(x).argmax())

Original array:
[9 5 1 3 5 7 7 2 3 7]
Most frequent value
7


# 14.How to get the n largest values of an array

In [24]:
import numpy as np
x = np.arange(30)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[29]


# 15.How to create a record array from a regular array?

In [22]:
import numpy as np
arra1 = np.array([("abc", 88.5, 90),
                 ("def", 87, 99),
             ("ghi", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['abc' '88.5' '90']
 ['def' '87' '99']
 ['ghi' '85.5' '91']]

Record array;
[(b'abc', 88.5, 90) (b'def', 87. , 99) (b'ghi', 85.5, 91)]
